---
- name: Include distro-specific variables
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution }}"
    extensions:
      - 'yml'

- name: Increase inotify limit
  ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
    sysctl_file: /etc/sysctl.d/50-inotify.conf
    reload: true

- name: Run distro-specific tasks
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution }}.yml"
